language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  script:
5   - echo 'Hello Firebase'

install:
   - npm install -g firebase-tools
8 after_success:
9   - firebase deploy --token $FIREBASE_TOKEN

