language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
script:
  - echo 'Hello Firebase'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token {$FIREBASE_TOKEN}

